### PR TITLE
Adding Commands

### PR DESCRIPTION
**Pull request by jmarkstar**

### CODE REVIEW

**Comment by jmarkstar** [comment]
Closed #29, #30, #31, #32

**Comment by jmarkstar** [comment]
Closed #38

**Comment by colemancda** [comment]
@jmarkstar I left comments on the codebase, pls review.

**Comment by jmarkstar** [comment]
Closed #39, #40

**Comment by jmarkstar** [comment]
Closed #41

**Comment by jmarkstar** [comment]
Closed #42

**Pull request merged**
